
name: Check SimplyFood build and tests

on:
  push:
    branches: ["main"]

  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

env:
  NODE_ENV: "test"
  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL  }}
  POSTGRES_PRISMA_URL: ${{  secrets.POSTGRES_PRISMA_URL }}
  POSTGRES_URL_NON_POOLING: ${{  secrets.POSTGRES_URL_NON_POOLING }}
  GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
  GITHUB_PASSWORD: ${{ secrets.GH_PASSWORD }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
  
  unit_tests_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run unit-tests
        run: npm run test

  e2e_tests_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
